config/routes.rb
Streetclean::Application.routes.draw do
  resources :feedbacks

  resources :authentications

  get "alert/create"

  get "alert/kill"
  
  get "alert/show"

  get "street/phone_carrier"

  get "street/number"
  get "street/intro"

  match 'auth/:provider/callback' => 'authentications#create'
  devise_for :users, :path_name => { :sign_up => "register"}

  get "street/index"
  get "street/show"
  get "street/mobile_home"
  get "street/email"
  get "street/text_message"

  get "locations/locate_car"
  
  get "layouts/about_us"
  get "layouts/contact_us"
  get "layouts/feedback"
  get "layouts/feedback_submit"
  get "layouts/tos"
  
  
  get "feedbacks/index"
  get "feedbacks/edit"
  get "feedbacks/new"
  
  resources :authentications
  

   root :to => "street#index"

end

app/models/street.rb
class Street < ActiveRecord::Base
  has_many :blocks
  
  def get_side(addr)
    if addr.even?
      return "R"
    else
      return "L"
    end
  end
  
  def self.double_choose
    
  end
  
  def self.get_doubles
    
  end
  
  
  
  def self.valid_suffix?(suf)
    suffixes =["ST","AVE" ,"WAY" ,"BLVD", "PL", "CT", "DR", "TER", "LN", "ALY", "PARK", "RD", "MAR", "HWY", "CIR", "EXPY", "PLAYA", "PLZ", "ARTS" ,"TUNL" ,"SORA", "EMBARCADERO"]
    suffixes.include?(suf)
  end
  
  def self.pop_suff(name)
    split = name.split
    suff = split.pop
    return split.join(" "), suff
  end
  
  def self.find_street(str)
    str.upcase!
    splt_str= str.split

    #Get address number and change it to integer
    num = splt_str[0]
    num = num.to_i
    

    # seperate the streetname and suffix from the rest of theinput
    # and join them all together
    len = splt_str.length
    name = splt_str.pop(len-1)
    name = name.join(" ")
    s = Street.where("streetname =?",name)
    if(s == []) 
      name, suff = self.pop_suff(name)
      s = Street.where("streetname =?",name)
      if(s == [])
        return -1
      end
    end
    return s,num
  end
  
  #This function returns the next clean time for a given address on the street
  def next_clean_time(addr)  
    #Figure out side of the street
    side = self.get_side(addr) 
    
    #Find all blocks that match Street Address 
    all_blocks = self.blocks
    blocks = all_blocks.where("side = ? AND bottom <= ? AND top >= ?", side, addr, addr)
    if blocks == []
      return nil
    else   
      #Compute the next cleaning times for the block and pick the smallest(i.e. the soonest) time
      cts = Array.new
      blocks.each{|x|cts << x.ct.next_time}
      best = cts.min
      return best, blocks[0].id
    end
  end
  
end

app/controllers/street_controller.rb
class StreetController < ApplicationController
  
 #Most(if not all) Helper functions from this file live in app/controllers/application_controller.rb
  
  # User must sign in before using search function
  # Commenting out for testing!
  before_filter :authenticate_user!, :except => [:sign_in]
  
  def index
  end
  
  def mobile_home
    
  end
  
  def email
    @user = current_user
    UserMailer.send_next_time(@user).deliver
  end
  
  def text_message
    @user = current_user
    UserMailer.send_next_time(@user).deliver
  end
  

  def show
    #Format User Input from Search Bar:  101 Market St -> [101, Market, St]
    double_trouble = FALSE
    s, num = Street.find_street(params[:q])
    @usr_qry = params[:q]
    #If Street not Found
    if (s == -1)
      double_trouble = TRUE
      if !mobile_device?
        respond_to do |format|
          format.html { render :file => "#{Rails.root}/public/no_street.html.erb"}
          format.xml {render :xml => @usr_qry} 
        end
      else
        respond_to do |format|
          format.html {render :file => "#{Rails.root}/public/no_street.html.erb"}
          format.xml {render :xml => @usr_qry}
        end
      end
    end
    if (s != -1 && s.length >1)
      fuck,suff = Street.pop_suff(params[:q])
      if Street.valid_suffix?(suff)
        s = Street.where("streetname =? AND suffix = ?", s[0].streetname,suff)
      else
        @possible_streets = Array.new
        s.each do |x|
          tmp_str=num.to_s
          tmp_str<<" "
          tmp_str<<x.streetname
          tmp_str<<" "
          tmp_str<<x.suffix
          @possible_streets << tmp_str
        end
        double_trouble = TRUE
        respond_to do |format|
          format.html {render :file => "#{Rails.root}/public/too_many_streets.html.erb"}
          format.xml {render :xml => @possible_streets}
        end
      end
    end
    
    if(!double_trouble)
      sid = s[0].id
      s = Street.find(sid)
      next_times,b_id = s.next_clean_time(num)
      if next_times == nil
        if !mobile_device
          respond_to do |format|
            format.html { render :file => "#{Rails.root}/public/no_street.html.erb"}
            format.xml {render :xml => @usr_qry} 
          end
        else
          respond_to do |format|
            format.html { render :file => "#{Rails.root}/public/no_street.mobile.erb"}
            format.xml {render :xml => @usr_qry}
          end
        end
        
      else
        b = Block.find(b_id)
        @user = current_user
        @loc = @user.location
        if !@loc
          @loc = Location.create(:user_id => @user.id)
        end
        street_str = s.streetname<<" "<<s.suffix
        @loc.updateloc(num,b.bottom,street_str,b.dir,next_times[0].to_time,next_times[1].to_time)
        @pretty_str = @loc.html_pretty_string 

        respond_to do |format|
            format.html # show.html.erb
            format.xml  { render :xml => @pretty_str }
        end
      end
    end
  
  end
  
  private
  
  def fuck
    return 0
  end
    

end

app/helpers/street_helper.rb
module StreetHelper
  def fuck_this(str)
    if mobile_device?
      if str == nil
        sex = "Sorry, but we couldn't find that street, please search again"
      end
    end
  end
      
  
end

app/views/street/email.html.erb
Fuck a bunch of emails. BEER!!!!!

app/views/street/email.mobile.erb
Fuck a bunch of emails. BEER!!!!!

app/views/street/index.html.erb
<div class="content_box">
	<!--<div id="ticket_photo">
		<%= image_tag "parking_ticket.jpg", :alt => 'Parking Ticket!' %>
	</div> -->
	<div id="user_input">
		<h2>Where is your car parked?</h2>
		<!-- <p> ex. <b>101 Market</b> or <b>100 Larkin St</b></p> -->
		<%= form_tag("/street/show/", :method => "get") do %>
			  <%= text_field_tag(:q, nil, :placeholder => "101 Market") %><br />
	
			  <%= submit_tag("Create Alert", :class => "user_submit") %>
		<% end %>
			
	</div>
</div >

app/views/street/index.mobile.erb
<div class="content_box">
	<h2><center><%=link_to "Search for Cleaning Times", street_mobile_home_path%><br />
		<br />
	<%=link_to "See Current Alarms", alert_show_path%><br />
		<br />
	<%=link_to "Edit User", edit_user_registration_path%></center></h2>
		<br />
</div>

app/views/street/mobile_home.html.erb
<div class="content_box">
	<!--<div id="ticket_photo">
		<%= image_tag "parking_ticket.jpg", :alt => 'Parking Ticket!' %>
	</div> -->
	<div id="user_input">
		<p>Where are you parked?</p>
		<p>(Ex. 3180 19th St or 3180 19th)</p>
		<p>
		<%= form_tag("/street/show/", :placeholder => "190 19th st", :method => "get") do %>
			  <%= text_field_tag(:q) %><br />
			  <%= submit_tag("Search") %>
			<% end %>
		</p>
	</div>
</div >

app/views/street/mobile_home.mobile.erb
<div class="content_box">
	<!--<div id="ticket_photo">
		<%= image_tag "parking_ticket.jpg", :alt => 'Parking Ticket!' %>
	</div> -->
	<div id="user_input">
		<h2>Where is your car parked?</h2>
		<p> ex. <b>101 Market</b> or <b>100 Larkin St</b></p>
		<%= form_tag("/street/show/", :method => "get") do %>
			  <%= text_field_tag(:q) %><br />
			  <%= submit_tag("Search") %>
			<% end %>
		</p>
	</div>
</div >

app/views/street/number.html.erb
<h1>Street#number</h1>
<p>Find me in app/views/street/number.html.erb</p>

app/views/street/phone_carrier.html.erb
<h1>Street#phone_carrier</h1>
<p>Find me in app/views/street/phone_carrier.html.erb</p>

app/views/street/show.html.erb
<!-- ALL OF THESE HELPER FUNCTIONS LIVE IN /app/helpers/street_helper.rb -->
<div class="content_box">
	<div id="pretty_str">
		<font color ="black">
		<h2>Your Results</h2>
		<%=@pretty_str[0]%><br><%=@pretty_str[1]%></font>
	</div>
	<br>
	<%=button_to "Create Alert", alert_create_path, :method => "get", :class => "user_submit"-%>
	<%=button_to "Text Times", street_text_message_path, :method => "get", :class => "user_submit"-%>
</div>

app/views/street/show.mobile.erb
<!-- ALL OF THESE HELPER FUNCTIONS LIVE IN /app/helpers/street_helper.rb -->
<%if @pretty_str != nil%>
	<div class="content_box">
		<div id="pretty_str">
			<font color ="black">
			<h2>Your Results</h2>
			<%=@pretty_str[0]%><br><%=@pretty_str[1]%></font>
		</div>
		<br>
		<%=button_to "Create a Cleaning Alert!", alert_create_path, :method => "get"-%>
		<%=button_to "Text Me This Time!", street_text_message_path, :method => "get"-%>
	</div>
<%else%>
	<p>
	<font color="orange">
	<h2>Unfortunately we don't have any records for:<br>
	<font color="red"><br> <%=@usr_qry%></font></h2>
	Please let use know if we should through the feedback button on the top right<br>
	<font>
	<font color="orange">
	<h2>Try Another Street</h2>
	<%= form_tag("/street/show/", :method => "get") do %>
		  <%= text_field_tag(:q) %>
		  <%= submit_tag("Search") %>
		<% end %>
	</p>
<%end%>

app/views/street/text_message.html.erb
<div class="content_box">

Your message is being sent. Why don't you go have a big glass of Whisky while you wait!

</div>

app/views/street/text_message.mobile.erb
<p>You're message is being delivered as we speak. Why don't you go home and have a big glass of Whisky while you wait!</p>

app/views/street/text_message_test.html.erb
<p>What is your phone number??</p>


<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
		<%= f.telephone_field :phone_number %></p>

		<p><%= f.label :carrier %><br />
		<%= f.select :carrier, ["AT&T", "Verizon", "T-Mobile", "Boost"] %>  </p>
		
		<p><%= f.submit "Sign up" %></p>
<% end %>

<%render :url => text_message_path %>