config/routes.rb
Streetclean::Application.routes.draw do
  resources :feedbacks

  resources :authentications

  get "alert/create"

  get "alert/kill"
  
  get "alert/show"

  get "street/phone_carrier"

  get "street/number"
  get "street/intro"

  match 'auth/:provider/callback' => 'authentications#create'
  devise_for :users, :path_name => { :sign_up => "register"}

  get "street/index"
  get "street/show"
  get "street/mobile_home"
  get "street/email"
  get "street/text_message"

  get "locations/locate_car"
  
  get "layouts/about_us"
  get "layouts/contact_us"
  get "layouts/feedback"
  get "layouts/feedback_submit"
  get "layouts/tos"
  
  
  get "feedbacks/index"
  get "feedbacks/edit"
  get "feedbacks/new"
  
  resources :authentications
  

   root :to => "street#index"

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  # GET /feedbacks
  # GET /feedbacks.xml
  def index
    @feedbacks = Feedback.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @feedbacks }
    end
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.xml
  def show
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @feedback }
    end
  end

  # GET /feedbacks/new
  # GET /feedbacks/new.xml
  def new
    @feedback = Feedback.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => devise_sessions_new_path }
    end
  end

  # GET /feedbacks/1/edit
  def edit
    @feedback = Feedback.find(params[:id])
  end

  # POST /feedbacks
  # POST /feedbacks.xml
  def create
    @feedback = Feedback.new(params[:feedback])

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to(@feedback, :notice => 'Feedback was successfully created.') }
        format.xml  { render :xml => @feedback, :status => :created, :location => @feedback }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @feedback.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /feedbacks/1
  # PUT /feedbacks/1.xml
  def update
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      if @feedback.update_attributes(params[:feedback])
        format.html { redirect_to(@feedback, :notice => 'Feedback was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @feedback.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.xml
  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to(feedbacks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Name" %><br />
    <%= f.text_field :authorname, :placeholder => "FTPopo" %>
  </div>
  <div class="field">
    <%= f.label "Email Address" %><br />
    <%= f.text_field :authoremail, :placeholder => "ticketcricket@gmail.com"%>
  </div>
  <div class="field" rows="4" cols="40">
    <%= f.label "Leave your comments!" %><br />
    <%= f.text_area :authorcomments, :placeholder => "Tell us what you think!"%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<h1>Listing feedbacks</h1>

<table>
  <tr>
    <th>Authorname</th>
    <th>Authoremail</th>
    <th>Authorcomments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feedbacks.each do |feedback| %>
  <tr>
    <td><%= feedback.authorname %></td>
    <td><%= feedback.authoremail %></td>
    <td><%= feedback.authorcomments %></td>
    <td><%= link_to 'Show', feedback %></td>
    <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
    <td><%= link_to 'Destroy', feedback, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<center><h1>Feedback</h1>

<%= render 'form' %>

<span style="font-size:20px;font-weight:bold">Give us a holler<br /><br />
<a href="mailto:ticket.cricket@gmail.com">ticket.cricket@gmail.com</a></span>

<%= link_to 'Back', feedbacks_path %></center>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Authorname:</b>
  <%= @feedback.authorname %>
</p>

<p>
  <b>Authoremail:</b>
  <%= @feedback.authoremail %>
</p>

<p>
  <b>Authorcomments:</b>
  <%= @feedback.authorcomments %>
</p>


<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>
<%= link_to "HOME", street_index_path%>