config/routes.rb
Streetclean::Application.routes.draw do
  resources :feedbacks

  resources :authentications

  get "alert/create"

  get "alert/kill"
  
  get "alert/show"

  get "street/phone_carrier"

  get "street/number"
  get "street/intro"

  match 'auth/:provider/callback' => 'authentications#create'
  devise_for :users, :path_name => { :sign_up => "register"}

  get "street/index"
  get "street/show"
  get "street/mobile_home"
  get "street/email"
  get "street/text_message"

  get "locations/locate_car"
  
  get "layouts/about_us"
  get "layouts/contact_us"
  get "layouts/feedback"
  get "layouts/feedback_submit"
  get "layouts/tos"
  
  
  get "feedbacks/index"
  get "feedbacks/edit"
  get "feedbacks/new"
  
  resources :authentications
  

   root :to => "street#index"

end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
end

app/helpers/layouts_helper.rb
module LayoutsHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args.map(&:to_s)) }
  end
  
  def javascript(*args)
    args = args.map { |arg| arg == :defaults ? arg : arg.to_s }
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/about_us.html.erb
<div class="about_image">
	<%= image_tag "dillman-image.png"%>
	<%= image_tag "peter-image.png"%>
	<%= image_tag "dian-image.png"%>
	<%= image_tag "jennifer-image.png"%>
	<%= image_tag "joseles-image.png"%>
	
</div>

<div class="content_box" id="about_box">
	
<p>Thanks for visiting Ticket Cricket. We created this site so that we could stop the onslaught of parking tickets. We're just a few people who wanted to help, so we worked many hours making this site what it is today - with no prior knowledge of how to do it. </p>
	
<h3>A FEW FACTS:</h3>
	
<h4>There are 89 neighborhoods that San Francisco recognizes for street cleaning.</h4>

<h4>In those 89 neighborhoods there are 238 unique cleaning times.</h4>

<h4>With those 238 unique times there are around 1425 streets that use them.</h4>

<p>That is A LOT to remember. So we have Ticket Cricket. Just enter the address where you parked and we will send you a text alert when it is time for you to move your car. It's that easy!
</p>	

</div>

app/views/layouts/about_us.mobile.erb
<div class="about_image">
	<%= image_tag "dillman-image.png"%>
	<%= image_tag "peter-image.png"%>
	<%= image_tag "dian-image.png"%>
	<%= image_tag "jennifer-image.png"%>
	<%= image_tag "joseles-image.png"%>
	
</div>

<div class="content_box" id="about_box">
	
<p>Thanks for visiting Ticket Cricket. We created this site so that we could stop the onslaught of parking tickets. We're just a few people who wanted to help, so we worked many hours making this site what it is today - with no prior knowledge of how to do it. </p>
	
<h3>A FEW FACTS:</h3>
	
<h4>There are 89 neighborhoods that San Francisco recognizes for street cleaning.</h4>

<h4>In those 89 neighborhoods there are 238 unique cleaning times.</h4>

<h4>With those 238 unique times there are around 1425 streets that use them.</h4>

<p>That is A LOT to remember. So we have Ticket Cricket. Just enter the address where you parked and we will send you a text alert when it is time for you to move your car. It's that easy!
</p>	

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" name="viewport" />
 
  <title>Ticket.Cricket</title>
	<link rel="shortcut icon" href="images/favicon.ico" />
  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag 'mobile' if mobile_device?%>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-22619120-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body id="body">
<div id="container">
	<body id="body">
		<header id="user_nav">

			<%= link_to "Home", street_index_path %>
			<%= link_to "My Alerts", alert_show_path %>
			<% if mobile_device? %>
		    	<%= link_to "Full Site",street_index_path, :mobile => 0 %>
		  	<% else %>
		    	<%= link_to "Mobile Site", :mobile => 1 %>
		  	<% end %>


				<div id="user_sign">

					<% if user_signed_in? %>
						Signed In as <%= link_to current_user.username.blank? ? current_user.email : current_user.username, edit_user_registration_path %>. Not you?
						<%= link_to "Sign Out", destroy_user_session_path %>
					<% else %>
						<%= link_to "Sign Up", new_user_registration_path %>
					<% end %>
				</div>
		</header>

		<!---<div id="logo">
			
		</div> -->
  <div id="yield_page">
		<%= yield %>
			
  </div> 
		
<!--	<hr style="border-width:0px;margin:0px;" /> -->
	
	<footer align="center" id="footer_nav">		
          <%= link_to "About Us", layouts_about_us_path%>
		
		<form id="paypal_form" action="https://www.paypal.com/cgi-bin/webscr" method="post">
		<input type="hidden" name="cmd" value="_s-xclick">
		<input type="hidden" name="hosted_button_id" value="K5ELFZECZQM66">
		<input type="image" src="https://www.paypalobjects.com/WEBSCR-640-20110429-1/en_US/i/btn/btn_donate_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
		<img alt="" border="0" src="https://www.paypalobjects.com/WEBSCR-640-20110429-1/en_US/i/scr/pixel.gif" width="1" height="1">
		</form>
		
		  <%= link_to "Contact Us", feedbacks_new_path %>
		<!-- <%= link_to "Feedback", feedbacks_new_path %> -->
		</ul>
	</footer>

	</body>
</div>

</html>

app/views/layouts/application.mobile.erb
<%= javascript_include_tag :defaults %>

<%= active_scaffold_includes %>
<!DOCTYPE html>
<html>
<head>
<meta content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=1;" name="viewport" />
 
  <title>Ticket.Cricket</title>
  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag 'mobile' if mobile_device?%>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-22619120-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</head>
<body id="body">
<div id="container">
	<body id="body">
		<div id="user_nav">
			<%= link_to "HOME", street_index_path %> | 
			<%= link_to "ALERTS", alert_show_path %> | 
			<% if mobile_device? %>
		    	<%= link_to "FULL SITE", :mobile => 0 %>
		  	<% else %>
		    	<%= link_to "Mobile Site", :mobile => 1 %>
		  	<% end %> | 
			<% if user_signed_in? %>
				<%= link_to "SIGN OUT", destroy_user_session_path %> 
			<% else %>
				<%= link_to "SIGN UP", new_user_registration_path %>
			<% end %>
		</div>
		<!---<div id="logo">
			
		#</div> -->
	<div id="yield_page">
			<%= yield %>
	</div>
	</body>
</div>

</html>

app/views/layouts/contact_us.html.erb
<div class="content_box">
	
	<span style="font-size:20px;font-weight:bold">Give us a holler<br /><br />
	<a href="mailto:ticket.cricket@gmail.com">ticket.cricket@gmail.com</a></span>
	
</div> 

app/views/layouts/contact_us.mobile.erb
<div class="content_box">
	
	<span style="font-size:20px;font-weight:bold">Give us a holler<br /><br />
	<a href="mailto:ticket.cricket@gmail.com">ticket.cricket@gmail.com</a></span>
	
</div> 